# Generated by Django 4.2.7 on 2023-11-20 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parents',
            field=models.ForeignKey(blank=True, limit_choices_to={'parents__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_set', to='products.category'),
        ),
    ]
